INSERT INTO `DBManagement_tag_definitions` (`id`,`title`,`type`,`topic_id`,`content`) VALUES (1,'accelerate','K',NULL,'accelerat.*'),
(2,'acute','K',NULL,'acute'),
(3,'amplitude','K',NULL,'amplitude'),
(4,'angle','K',NULL,'angle.?'),
(5,'approximate','K',NULL,'approximat.*'),
(6,'arc','K',NULL,'arc'),
(7,'area','K',NULL,'area.?'),
(8,'arithmetic_progression','K',NULL,'arithmetic progression.?'),
(9,'arrange','K',NULL,'arrang.*'),
(10,'ascend','K',NULL,'ascend.*'),
(11,'bear','K',NULL,'bear.*'),
(12,'binomial','K',NULL,'binomial'),
(13,'bound','K',NULL,'bound.*'),
(14,'calculator','K',NULL,'calculator'),
(15,'cartesian','K',NULL,'cartesian'),
(16,'centre','K',NULL,'centre'),
(17,'chord','K',NULL,'chord.?'),
(18,'circle','K',NULL,'circle.?'),
(19,'circular','K',NULL,'circular'),
(20,'circumference','K',NULL,'circumference.?'),
(21,'coefficient','K',NULL,'coefficient'),
(22,'collinear','K',NULL,'collinear'),
(23,'common_ratio','K',NULL,'common ratio.?'),
(24,'congruent','K',NULL,'congruen.*'),
(25,'constant','K',NULL,'constant.?'),
(26,'coordinate','K',NULL,'coordinate.?'),
(27,'curve','K',NULL,'curve.?'),
(28,'decelerate','K',NULL,'decelerat.*'),
(29,'decrease','K',NULL,'decreas.*'),
(30,'define','K',NULL,'defin.*'),
(31,'descend','K',NULL,'descend.*'),
(32,'diagram','K',NULL,'diagram.?'),
(33,'differentiate','K',NULL,'differentiat.*'),
(34,'direction','K',NULL,'direction.?'),
(35,'displacement','K',NULL,'displacement.?'),
(36,'distance','K',NULL,'distance.?'),
(37,'distinct_point','K',NULL,'distinct point.?'),
(38,'divide','K',NULL,'divid.*'),
(39,'domain','K',NULL,'domain.?'),
(40,'draw','K',NULL,'draw.?'),
(41,'due','K',NULL,'due'),
(44,'e','K',NULL,'e\\^.*'),
(45,'east','K',NULL,'east'),
(46,'element','K',NULL,'element.?'),
(47,'empty','K',NULL,'empty'),
(48,'enclose','K',NULL,'enclos.*'),
(49,'factor','K',NULL,'factor.*'),
(50,'form','K',NULL,'form.?'),
(51,'function','K',NULL,'function.?'),
(52,'geometric_progression','K',NULL,'geometric progression.?'),
(53,'gradient','K',NULL,'gradient.?'),
(54,'graph','K',NULL,'graph.?'),
(55,'identity','K',NULL,'identit.*'),
(56,'increase','K',NULL,'increase.?'),
(57,'instant','K',NULL,'instant.?'),
(58,'instantaneous','K',NULL,'instantaneous'),
(59,'intersect','K',NULL,'intersect.*'),
(60,'inverse','K',NULL,'inverse'),
(61,'leave','K',NULL,'leav.*'),
(62,'lg','K',NULL,'lg.*'),
(63,'ln','K',NULL,'ln.*'),
(64,'log','K',NULL,'log.*'),
(65,'magnitude','K',NULL,'magnitude.?'),
(66,'map','K',NULL,'map.?'),
(67,'matrice','K',NULL,'matri.{0,3}'),
(68,'matrix','K',NULL,'matrix'),
(69,'matrix_multiplication','K',NULL,'matrix multiplication.?'),
(70,'maximum','K',NULL,'maximum'),
(71,'measure','K',NULL,'measur.*'),
(72,'mid-point','K',NULL,'mid-?point.?'),
(73,'minimum','K',NULL,'minimum'),
(74,'modulus','K',NULL,'mod'),
(75,'move','K',NULL,'mov,{0,3}'),
(76,'normal','K',NULL,'normal'),
(77,'north','K',NULL,'north'),
(78,'number','K',NULL,'number.?'),
(79,'origin','K',NULL,'origin.?'),
(80,'pair','K',NULL,'pair.?'),
(81,'parallel','K',NULL,'parallel'),
(82,'parallelogram','K',NULL,'parallelogram.?'),
(83,'partial_fraction','K',NULL,'partial fraction.?'),
(84,'pass','K',NULL,'pass.*'),
(85,'percentage','K',NULL,'percentage'),
(86,'perimeter','K',NULL,'perimeter.?'),
(87,'period','K',NULL,'period.?'),
(88,'perpendicular','K',NULL,'perpendicular'),
(89,'perpendicular_bisector','K',NULL,'perpendicular bisector.?'),
(90,'point','K',NULL,'point.?'),
(91,'polynomial','K',NULL,'polynomial'),
(92,'position','K',NULL,'position.?'),
(93,'power','K',NULL,'power'),
(94,'product','K',NULL,'product'),
(95,'prove','K',NULL,'prov.{0,3}'),
(96,'quadratic','K',NULL,'quadratic'),
(97,'quadrilateral','K',NULL,'quadrilateral'),
(98,'radian','K',NULL,'radian'),
(99,'radius','K',NULL,'radius'),
(100,'range_of_value','K',NULL,'range of value.?'),
(101,'rate_of_change','K',NULL,'rate of change.?'),
(102,'reach','K',NULL,'reach.*'),
(103,'real','K',NULL,'real'),
(104,'region','K',NULL,'region.?'),
(105,'remainder','K',NULL,'remainder.?'),
(106,'respect','K',NULL,'respect'),
(107,'rest','K',NULL,'rest.{0,3}'),
(108,'retard','K',NULL,'retard.*'),
(109,'root','K',NULL,'root.?'),
(110,'rotate','K',NULL,'rotat.*'),
(111,'scalar','K',NULL,'scalar'),
(112,'second','K',NULL,'second.?'),
(113,'sector','K',NULL,'sector.?'),
(114,'semicircle','K',NULL,'semi-?circle.?'),
(115,'set','K',NULL,'set.?'),
(116,'set_notation','K',NULL,'set notation.?'),
(117,'shaded','K',NULL,'shaded'),
(118,'simplify','K',NULL,'simplify'),
(119,'simultaneous','K',NULL,'simultaneous'),
(120,'sketch','K',NULL,'sketch.*'),
(121,'small','K',NULL,'small.*'),
(122,'solution','K',NULL,'solution.?'),
(123,'solve','K',NULL,'solv.*'),
(124,'speed','K',NULL,'speed.?'),
(125,'square','K',NULL,'square.?'),
(126,'stationary','K',NULL,'stationary'),
(127,'straight_line','K',NULL,'straight line.?'),
(128,'subset','K',NULL,'subset.?'),
(129,'surd','K',NULL,'surd.?'),
(130,'tangent','K',NULL,'tangent'),
(131,'term','K',NULL,'term.?'),
(132,'time','K',NULL,'time'),
(133,'trapezium','K',NULL,'trapezium.?'),
(134,'travel','K',NULL,'travel.*'),
(135,'triangle','K',NULL,'triangle.?'),
(136,'turning_point','K',NULL,'turning point.?'),
(137,'uniform','K',NULL,'uniform'),
(138,'unit','K',NULL,'unit.?'),
(139,'value','K',NULL,'value.?'),
(140,'vary','K',NULL,'vary.*'),
(141,'vector','K',NULL,'vector.?'),
(142,'velocity','K',NULL,'velocity'),
(143,'venn_diagram','K',NULL,'venn diagram.?'),
(144,'vertice','K',NULL,'vert.*'),
(145,'volume','K',NULL,'volume'),
(146,'way','K',NULL,'way'),
(147,'wind','K',NULL,'wind'),
(148,'Equation_Of_Normal','F',25,'Differentiation - $$y - y_1 = -\\frac{1}{m}(x - x_1)$$ (Equation of Normal)'),
(149,'Equation_Of_Tangent','F',25,'Differentiation - $$y - y_1 = m(x - x_1)$$ (Equation of Tangent)'),
(150,'Gradient_Of_Curve','F',25,'Differentiation - $$\\frac{y_2 - y_1}{x_2 - x_1}$$ (Gradient of Curve)'),
(151,'Chain_Rule','F',25,'Differentiation - $$\\frac{\\mathrm{d} y}{\\mathrm{d} x} = \\frac{\\mathrm{d} y}{\\mathrm{d} u} \\times \\frac{\\mathrm{d} u}{\\mathrm{d} x}$$ (Chain Rule)'),
(152,'Derivative_Of_Power','F',25,'Differentiation - $$\\frac{\\mathrm{d} }{\\mathrm{d} x} (ax^n) = anx^{n-1}$$'),
(153,'Product_Rule','F',25,'Differentiation - $$\\frac{\\mathrm{d} }{\\mathrm{d} x} (uv) = u \\frac{\\mathrm{d} v}{\\mathrm{d} x} \\times v \\frac{\\mathrm{d} u}{\\mathrm{d} x}$$ (Product Rule)'),
(154,'Derivative_Of_Cosine_Power','F',25,'Differentiation - $$\\frac{\\mathrm{d} }{\\mathrm{d} x} (\\cos^n x) = -n \\cos^{n-1} x \\sin x$$'),
(155,'Quotient_Rule','F',25,'Differentiation - $$\\frac{\\mathrm{d} }{\\mathrm{d} x} (\\frac{u}{v}) = \\frac {v \\frac{\\mathrm{d} u}{\\mathrm{d} x} - u \\frac{\\mathrm{d} v}{\\mathrm{d} x}}{v^2}$$ (Quotient Rule)'),
(156,'Derivative_Of_Sine_Power','F',25,'Differentiation - $$\\frac{\\mathrm{d} }{\\mathrm{d} x} (\\sin^n x) = n \\sin^{n-1} x \\cos x$$'),
(157,'Derivative_Of_Tangent','F',25,'Differentiation - $$\\frac{\\mathrm{d} }{\\mathrm{d} x} (\\tan (ax + b)) = a \\sec^2 (ax + b)$$'),
(158,'Derivative_Of_Tangent_Power','F',25,'Differentiation - $$\\frac{\\mathrm{d} }{\\mathrm{d} x} (\\tan^n x) = n \\tan^{n-1} x \\sec^2 x$$'),
(159,'Derivative_Of_Exponentials','F',25,'Differentiation - $$\\frac{\\mathrm{d} }{\\mathrm{d} x} e^{f(x)} = f\'(x) e^{f(x)}$$'),
(160,'Derivative_Of_Cosine','F',25,'Differentiation - $$\\frac{\\mathrm{d} }{\\mathrm{d} x} \\cos (ax+b) = -a \\sin (ax+b)$$'),
(161,'Derivative_Of_Natural_Log','F',25,'Differentiation - $$\\frac{\\mathrm{d} }{\\mathrm{d} x} \\ln f(x) = \\frac{f\'(x)}{f(x)}$$'),
(162,'Derivative_Of_Sine','F',25,'Differentiation - $$\\frac{\\mathrm{d} }{\\mathrm{d} x} \\sin (ax+b) = a \\cos (ax+b)$$'),
(163,'Higher_Derivatives','F',25,'Differentiation - $$\\frac{\\mathrm{d}^2 y}{\\mathrm{d} x^2} = \\frac{\\mathrm{d} (\\frac{\\mathrm{d} y}{\\mathrm{d} x})}{\\mathrm{d} x}$$'),
(164,'Indices_Identities_3','F',15,'Indices - $$(a^m)^n = a^{mn}$$, where a, m, n are positive integers'),
(165,'Indices_Identities_6','F',15,'Indices - $$a^0 = 1$$, where a is positive integer'),
(166,'Indices_Identities_2','F',15,'Indices - $$a^m \\div a^n = a^{m-n}$$, where a, m, n are positive integers'),
(167,'Indices_Identities_5','F',15,'Indices - $$a^m \\div b^m = (\\frac{a}{b})^m$$, where a, b, m, n are positive integers'),
(168,'Indices_Identities_1','F',15,'Indices - $$a^m \\times a^n = a^{m+n}$$, where a, m, n are positive integers'),
(169,'Indices_Identities_4','F',15,'Indices - $$a^m \\times b^m = (a \\times b)^m$$, where a, b, m, n are positive integers'),
(170,'Indices_Identities_7','F',15,'Indices - $$a^{-n} = \\frac{1}{a^n}$$, where a, n are positive integers'),
(171,'Indices_Identities_8','F',15,'Indices - $$a^{\\frac{1}{n}} = \\sqrt[n]{a}$$, where a, n are positive integers'),
(172,'Indices_Identities_9','F',15,'Indices - $$a^{\\frac{m}{n}} = \\sqrt[n]{a^m} = (\\sqrt[n]{a})^m$$, where a, m, n are positive integers'),
(173,'Indices_Identities_10','F',15,'Indices - If $$a^x = a^y$$ then $$x = y$$ where $$a > 0$$ and $$a \\neq 1$$'),
(174,'Log_Of_One','F',20,'Logarithms - $$\\log_a 1 = 0$$'),
(175,'Log_Of_Integer_Same_To_Base','F',20,'Logarithms - $$\\log_a a = 1$$'),
(176,'Log_Change_Of_Base','F',20,'Logarithms - $$\\log_a b = \\frac{log_c b}{log_c a}$$, where $$a \\neq 1$$ and $$a > 0$$, $$c \\neq 1$$ and $$c > 0$$ (Change of Base)'),
(177,'Log_Product_law','F',20,'Logarithms - $$\\log_a m + \\log_a n = \\log_a (m \\times n)$$ (Product Law)'),
(178,'Log_Quotient_Law','F',20,'Logarithms - $$\\log_a m - \\log_a n = \\log_a \\frac{m}{n}$$ (Quotient Law)'),
(179,'Log_Power_Law','F',20,'Logarithms - $$\\log_a m^n = n \\log_a m$$ (Power Law)'),
(180,'Log_To_Indices','F',20,'Logarithms - $$\\log_a y = x$$ means $$a^x = y$$'),
(181,'Deriving_Partial_Fraction_From_Linear_Fraction','F',17,'Partial Fraction - Case 1: Linear Fraction e.g. $$\\frac{mx + n}{(ax + b)(cx + d)}$$, express in $$\\frac{A}{ax + b} + \\frac{C}{cx + d}$$'),
(182,'Deriving_Partial_Fraction_From_Repeated_Fraction','F',17,'Partial Fraction - Case 2: Repeated Fraction e.g. $$\\frac{mx + n}{(ax + b)(cx + d)^2}$$, express in $$\\frac{A}{ax + b} + \\frac{B}{cx + d} + \\frac{C}{(cx + d)^2}$$'),
(183,'Deriving_Partial_Fraction_From_Quadratic_Factor','F',17,'Partial Fraction - Case 3: Quadratic Factor which does not factorise e.g. $$\\frac{mx + n}{(ax + b)(x^2 + c^2)}$$, express in $$\\frac{A}{ax + b} + \\frac{Bx + C}{x^2 + c^2}$$'),
(184,'Factor_Theorem','F',16,'Polynomial - $$ax-b$$, where $$a \\neq 0$$, is a factor of the polynomial $$f(x) \\Leftrightarrow f(\\frac{b}{a}) = 0$$ (Factor Theorem)'),
(186,'Remainder_Theorem','F',16,'Polynomial - When the polynomial $$f(x)$$ is divided by $$ax-b$$ where $$a \\neq 0$$, the remainder R is given by R = $$f(\\frac{b}{a})$$. (Remainder Theorem)'),
(188,'Sum_Of_Roots','F',14,'Quadratic Equations - $$\\alpha + \\beta = -\\frac{b}{a}$$ (Sum of Roots)'),
(189,'Product_Of_Roots','F',14,'Quadratic Equations - $$\\alpha\\beta = \\frac{c}{a}$$ (Product of Roots)'),
(190,'Surds_Identities_3','F',15,'Surds - $$(a \\sqrt{m} + b \\sqrt{n})(a \\sqrt{m} - b \\sqrt{n}) = a^2m - b^2n$$'),
(191,'Surds_Identities_2','F',15,'Surds - $$\\sqrt{a} \\div \\sqrt{b} = \\sqrt{\\frac{a}{b}}$$, where $$a \\geq 0$$, b > 0'),
(192,'Surds_Identities_1','F',15,'Surds - $$\\sqrt{a} \\times \\sqrt{b} = \\sqrt{ab}$$, where $$a, b \\geq 0$$'),
(193,'Decreasing_Function','C',25,'Differentiation - Decreasing functions has  $$\\frac{\\mathrm{d} y}{\\mathrm{d} x} < 0 $$'),
(194,'No_Turning_Point','C',25,'Differentiation - If $$\\frac{\\mathrm{d} y}{\\mathrm{d} x} = 0 $$ has no solution, then there is no turning point.'),
(195,'Point_Of_Inflexion','C',25,'Differentiation - If $$\\frac{\\mathrm{d} y}{\\mathrm{d} x}$$ does not change as it passes through the stationary point, then it is a point of inflexion.'),
(196,'Maximum_Point','C',25,'Differentiation - If $$\\frac{\\mathrm{d}^2 y}{\\mathrm{d} x^2} < 0$$, then it is a maximum point.'),
(197,'Minimum_Point','C',25,'Differentiation - If $$\\frac{\\mathrm{d}^2 y}{\\mathrm{d} x^2} > 0$$, then it is a minimum point.'),
(198,'Increasing_Function','C',25,'Differentiation - Increasing functions has  $$\\frac{\\mathrm{d} y}{\\mathrm{d} x} > 0 $$'),
(199,'Motion_With_Variable_Velocity_And_Acceleration','C',25,'Differentiation - Motion with Variable Velocity and Acceleration'),
(201,'Stationary_Point','C',25,'Differentiation - When $$\\frac{\\mathrm{d} y}{\\mathrm{d} x} = 0 $$, it is a Stationary Point.'),
(202,'Solve_Partial_Fraction_By_Comparing_Coefficients','C',17,'Partial Fraction - Solving unknown constants by comparing coefficients of like terms'),
(203,'Solve_Partial_Fraction_By_Substitution','C',17,'Partial Fraction - Solving unknown constants by substituting values of x'),
(204,'Factorise_Cubic_Expression_By_Comparing_Coefficient','C',16,'Polynomial - If one of the factor is given, by comparing coefficient, the other factor must be second degree of the form $$ax^2 + bx + c$$'),
(205,'Factorise_Cubic_Expression_By_Long_Division','C',16,'Polynomial - Using Long division'),
(206,'Factorise_Cubic_Expression_By_Trial_And_Error','C',16,'Polynomial - Using Trial and Error, factor of $$f(x)$$ should give remainder of zero.'),
(207,'Absolute_Values_And_Functions','C',14,'Quadratic Equations - $$|x| = \\begin{Bmatrix}x \\: if \\: x > 0\\\\ 0 \\: if \\: x = 0\\\\ -x \\: if \\: x < 0\\end{Bmatrix}$$'),
(208,'Inequality_For_(x-h)(x-k)<0','C',14,'Quadratic Equations - For $$(x - h)(x - k) < 0$$, when $$y < 0$$, $$h < x < k$$.'),
(209,'Inequality_For_(x-h)(x-k)>0','C',14,'Quadratic Equations - For $$(x - h)(x - k) > 0$$, when $$y > 0$$, $$x < h$$ or $$x > k$$.'),
(210,'Nature_Of_Roots_For_Line_And_Curve','C',14,'Quadratic Equations - Nature of the roots depends on the value of the discriminant $$b^2 - 4ac$$ after solving the line and curve equations simultaneously.'),
(211,'No_Real_Roots','C',14,'Quadratic Equations - When $$b^2 - 4ac < 0$$, there are no real roots.'),
(212,'Line_Does_Not_Intersects_Curve','C',14,'Quadratic Equations - When $$b^2 - 4ac < 0, Line does not intersect the curve.'),
(213,'Real_And_Equal_Roots','C',14,'Quadratic Equations - When $$b^2 - 4ac = 0$$, there are 2 real and equal roots.'),
(214,'Line_Tangent_To_Curve','C',14,'Quadratic Equations - When $$b^2 - 4ac = 0, Line is tangent to the curve.'),
(215,'Real_And_Distinct_Roots','C',14,'Quadratic Equations - When $$b^2 - 4ac > 0$$, there are 2 real and distinct roots.'),
(216,'Line_Cuts_Curve_At_Two_Points','C',14,'Quadratic Equations - When $$b^2 - 4ac > 0, Line cuts the curve at 2 distinct points'),
(217,'Simultaneous_Of_Linear_And_Non-Linear','C',18,'Simultaneous - Express one unknown in terms of the other with the linear equation, then substitute the result to the non-linear equation to solve it'),
(220,'Simultaneous_By_Substitution','C',18,'Simultaneous - Express one unknown in terms of the other, then substitute the result to solve for the unknown (Substitution)'),
(222,'Simultaneous_By_Elimination','C',18,'Simultaneous - Express one unknown of equal value in both equations, then eliminate the unknown to get the value of the other known (Elimination)'),
(224,'Mid-point_Of_Line','F',23,'Coordinate Geometry - Mid-point = $$(\\frac{x_1 + x_2}{2}, \\frac{y_1 + y_2}{2})$$'),
(225,'Gradient_Of_Line','F',23,'Coordinate Geometry - Gradient = $$\\frac{y_2 - y_1}{x_2 - x_1}$$'),
(226,'Equation_Of_Line','F',23,'Coordinate Geometry - Equation of Line = $$y - y_1 = m(x - x_1)$$, where m = gradient of line.'),
(227,'Distance_Of_Line','F',23,'Coordinate Geometry - Distance = $$\\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$$'),
(228,'Parallel_Lines','C',23,'Coordinate Geometry - Line $$l_1$$ and $$l_2$$ are parallel if $$m_1 = m_2$$.'),
(229,'Perpendicular_Lines','C',23,'Coordinate Geometry - Line $$l_1$$ and $$l_2$$ are perpendicular if $$m_1 m_2 = -1$$.'),
(230,'Equation_Of_Line_From_Non-Linear_Equation','C',23,'Coordinate Geometry - Express equation in form of $$Y = mX + c$$ where X and Y are expressions in x and/or y.'),
(231,'Equation_Of_Circle','F',23,'Coordinate Geometry - Equation of Circle = $$(x - a)^2 + (y - b)^2 = r^2$$, where $$(a,b)$$ is the centre and $$r$$ is the radius.'),
(232,'Area_Of_Plane','F',24,'Plane Geometry - Area of Plane = $$\\frac{1}{2}\\begin{vmatrix}x_1 & x_2 & x_3 & ...\\\\ y_1 & y_2 & y_3 & ...\\end{vmatrix} = \\frac{1}{2} [(x_1\\cdot y_2 + x_2 \\cdot y_3 + ... + x_{n-1} \\cdot y_n)-(x_2 \\cdot y_1 + x_3 \\cdot y_2 + ... + x_n \\cdot y_{n-1})]$$'),
(233,'Binomial_Theorem','F',19,'Binomial - $$(x + y)^n = x^n + \\binom{n}{1} x^{n-1}y + \\binom{n}{2} x^{n-2}y^2 + ... + \\binom{n}{r} x^{n-r}y^r + ... + y^n$$'),
(234,'Binomial_Term','F',19,'Binomial - $$(r + 1)$$th term is $${}^{n}\\textrm{C}_r x^{n-r}y^r$$, where $${}^{n}\\textrm{C}_r = \\frac{n(n-1)...(n-r+1)}{1 \\cdot 2...r}$$'),
(235,'Term_Independent','C',19,'Binomial - Term Independent refers to the constant term in the binomial expansion.'),
(236,'Positive_Negative_Angles','C',22,'Trigonometry - Angles measured anticlockwise from the positive direction of x-axis are positive while angles measured clockwise from the positive direction of the x-axis are negative'),
(237,'Sine_Angles','F',22,'Trigonometry - $$\\sin \\theta = \\frac{y}{r}, x \\neq 0$$'),
(238,'Cosine_Angles','F',22,'Trigonometry - $$\\cos \\theta = \\frac{x}{r}, x \\neq 0$$'),
(239,'Tangent_Angles','F',22,'Trigonometry - $$\\tan \\theta = \\frac{y}{x}, x \\neq 0$$'),
(240,'Trigonometry_Identities_1','F',22,'Trigonometry - $$\\sin (-A) = -\\sin A$$'),
(241,'Trigonometry_Identities_2','F',22,'Trigonometry - $$\\cos (-A) = \\cos A$$'),
(242,'Trigonometry_Identities_3','F',22,'Trigonometry - $$\\tan (-A) = -\\tan A$$'),
(243,'Trigonometry_Identities_4','F',22,'Trigonometry - $$\\sin (90^{\\circ} - A) = \\cos A$$'),
(244,'Trigonometry_Identities_5','F',22,'Trigonometry - $$\\cos (90^{\\circ} - A) = \\sin A$$'),
(245,'Trigonometry_Identities_6','F',22,'Trigonometry - $$\\tan A = \\frac{\\sin A}{\\cos A}$$'),
(246,'Trigonometry_Identities_7','F',22,'Trigonometry - $$\\sec A = \\frac{1}{\\cos A}$$'),
(247,'Trigonometry_Identities_8','F',22,'Trigonometry - $$\\csc A = \\frac{1}{\\sin A}$$'),
(248,'Trigonometry_Identities_9','F',22,'Trigonometry - $$\\cot A = \\frac{1}{\\tan A}$$'),
(249,'Trigonometry_Identities_10','F',22,'Trigonometry - $$\\sin^2 A + \\cos^2 A = 1$$'),
(250,'Trigonometry_Identities_11','F',22,'Trigonometry - $$1 + \\tan^2 A = \\sec^2 A$$'),
(251,'Trigonometry_Identities_12','F',22,'Trigonometry - $$1 + \\cot^2 A = csc^2 A$$'),
(252,'Trigonometry_Identities_13','F',22,'Trigonometry - $$\\sin (A \\pm B) = \\sin A \\cos B \\pm \\cos A \\sin B$$'),
(253,'Trigonometry_Identities_14','F',22,'Trigonometry - $$\\cos (A \\pm B) = \\cos A \\cos B \\mp \\sin A \\sin B$$'),
(254,'Trigonometry_Identities_15','F',22,'Trigonometry - $$\\tan (A \\pm B) = \\frac{\\tan A \\pm \\tan B}{1 \\mp \\tan A \\tan B}$$'),
(255,'Trigonometry_Identities_16','F',22,'Trigonometry - $$\\sin 2A = 2 \\sin A \\cos A$$'),
(256,'Trigonometry_Identities_17','F',22,'Trigonometry - $$\\cos 2A = \\cos^2 A - \\sin^2 A = 1 - 2 \\sin^2 A = 2 \\cos^2 A - 1$$'),
(257,'Trigonometry_Identities_18','F',22,'Trigonometry - $$\\tan 2A = \\frac{2 \\tan A}{1 - \\tan^2 A}'),
(258,'Trigonometry_Factor_Formulae_1','F',22,'Trigonometry - $$\\sin X + \\sin Y = 2 \\sin \\frac{X + Y}{2} \\cos {X - Y}{2}$$'),
(259,'Trigonometry_Factor_Formulae_2','F',22,'Trigonometry - $$\\sin X - \\sin Y = 2 \\cos \\frac{X + Y}{2} \\sin {X - Y}{2}$$'),
(260,'Trigonometry_Factor_Formulae_3','F',22,'Trigonometry - $$\\cos X + \\cos Y = 2 \\cos \\frac{X + Y}{2} \\cos {X - Y}{2}$$'),
(261,'Trigonometry_Factor_Formulae_4','F',22,'Trigonometry - $$\\cos X - \\cos Y = -2 \\sin \\frac{X + Y}{2} \\sin {X - Y}{2}$$'),
(262,'Solving_Multiple_Angles','C',22,'Trigonometry - Equations involving multiple angles are usually solved by converting the equation into another equation that contains only one trigonometrical ratio or by using the values from calculators.'),
(263,'Trigonometry_Form_1','F',22,'Trigonometry - $$a \\cos \\theta \\pm b \\sin \\theta = R \\cos (\\theta \\mp \\alpha)$$ where $$R = \\sqrt{a^2 + b^2}, \\tan \\alpha = \\frac{b}{a}$$, $$a$$ and $$b$$ are positive and $$\\alpha$$ is acute'),
(264,'Trigonometry_Form_2','F',22,'Trigonometry - $$a \\sin \\theta \\pm b \\cos \\theta = R \\sin (\\theta \\pm \\alpha)$$ where $$R = \\sqrt{a^2 + b^2}, \\tan \\alpha = \\frac{b}{a}$$, $$a$$ and $$b$$ are positive and $$\\alpha$$ is acute'),
(267,'Matrix_Determinant','F',30,'Matrix - If $$A = \\begin{pmatrix}a & b\\\\ c & d\\end{pmatrix}$$, det A = ad - bc.'),
(268,'Inverse_Matrix','F',30,'Matrix - If $$A = \\begin{pmatrix}a & b\\\\ c & d\\end{pmatrix}$$, $$A^{-1} = \\frac{1}{ad - bc} A = \\begin{pmatrix}d & -b\\\\ -c & a\\end{pmatrix}, provided det $$A \\neq 0$$.'),
(269,'Identity_Matrix','F',30,'Matrix - $$AA^{-1} = I$$'),
(270,'Simultaneous_By_Matrix','C',30,'Matrix - A pair of simultaneous equations can be expressed in matrix form as AX = B. Then the solution is $$X = A^{-1}B$$, if $$det(A) \\neq 0$$.'),
(271,'Scalar_Matrix_Multiplication','F',30,'Matrix - If $$A = \\begin{pmatrix}a & b\\\\ c & d\\end{pmatrix}$$, $$2A = \\begin{pmatrix}2 \\cdot a & 2 \\cdot b\\\\ 2 \\cdot c & 2\\cdot d\\end{pmatrix}$$'),
(272,'Two_Matrices_Multiplication','F',30,'Matrix - If $$A = \\begin{pmatrix}a \\\\ b\\end{pmatrix}$$ and $$B = \\begin{pmatrix}c & d \\end{pmatrix}$$, $$AB = \\begin{pmatrix}a \\cdot c & a \\cdot d\\\\ b \\cdot c & b \\cdot d\\end{pmatrix}$$'),
(273,'Integration_By_Reverse_Of_Differentiation','F',26,'Integration - If $$\\frac{\\mathrm{d} }{\\mathrm{d} x} [F(x)] = f(x)$$, then $$\\int f(x) dx = F(x) + c$$ where $$c$$ is a constant.'),
(274,'Basic_Integration_Formulae_1','F',26,'Integration - $$\\int [f(x) + g(x)] dx = \\int f(x) dx + \\int g(x) dx$$'),
(275,'Basic_Integration_Formulae_2','F',26,'Integration - $$\\int kf(x) dx = k\\int f(x) dx$$'),
(276,'Basic_Integration_Formulae_3','F',26,'Integration - $$\\int ax^n dx = \\frac{ax^{n+1}}{n + 1} + c, n \\neq -1$$'),
(277,'Basic_Integration_Formulae_4','F',26,'Integration - $$\\int (ax + b)^n dx = \\frac{(ax + b)^{n+1}}{(n + 1)a} + c, n\\neq -1$$'),
(278,'Integral_Of_Cosine','F',26,'Integration - $$\\int \\cos (ax + b) dx = \\frac{1}{a} \\sin (ax + b) + c$$'),
(279,'Integral_Of_Sine','F',26,'Integration - $$\\int \\sin (ax + b) dx = -\\frac{1}{a} \\cos (ax + b) + c$$'),
(280,'Integral_Of_Secant_Square','F',26,'Integration - $$\\int \\sec^2 (ax + b) dx = \\frac{1}{a} \\tan (ax + b) + c$$'),
(281,'Integral_Of_Fraction_Function_1','F',26,'Integration - $$\\int \\frac{1}{x} dx = \\ln x + c$$'),
(282,'Integral_Of_Fraction_Function_2','F',26,'Integration - $$\\int \\frac{1}{ax + b} dx = \\frac{1}{a} \\ln (ax + b) + c$$'),
(283,'Integral_Of_Fraction_Function_3','F',26,'Integration - $$\\int \\frac{f\'(x)}{f(x)} dx = \\ln f(x) + c$$'),
(284,'Integral_Of_Exponential_Function_1','F',26,'Integration - $$\\int e^x dx = e^x + c$$'),
(285,'Integral_Of_Exponential_Function_2','F',26,'Integration - $$\\int e^{ax} dx = \\frac{1}{a} e^{ax} + c$$'),
(286,'Integral_Of_Exponential_Function_3','F',26,'Integration - $$\\int e^{ax + b} dx = \\frac{1}{a} e^{ax + b} + c$$'),
(287,'Definite_Integral','F',26,'Integration - If $$\\int f(x) dx = F(x) + c$$, then $$\\int_{a}^{b} f(x) dx = [F(x)]_a^b = F(b)-F(a)$$'),
(288,'Area_Bounded_By_Curve_y=f(x)','F',26,'Integration - The area bounded by the curve $$y=f(x)$$, the x-axis and the lines $$x = a$$ and $$x = b (a < b)$$ is given by $$\\int_{a}^{b} f(x) dx$$'),
(289,'Area_Bounded_By_Curve_x=f(y)','F',26,'Integration - The area bounded by the curve $$x=f(y)$$, the y-axis and the lines $$y = a$$ and $$y = b$$ is given by $$\\int_{a}^{b} f(y) dy$$'),
(290,'Kinematics_Distance_Using_Integration','F',26,'Integration - If the velocity $$v$$ of a particle is given as a function of time $$t$$, i.e. $$v = f(t)$$, then $$\\int f(t) dt$$ will give the expression for the distance covered.'),
(291,'Kinematics_Velocity_Using_Integration','F',26,'Integration - If the acceleration $$a$$ of a particle is given as a function of time $$t$$, i.e. $$a = f(t)$$, then $$\\int f(t) dt$$ will give the expression for the velocity.');
